### ISSUE TITLE
Function titles in the sidebar instead of names

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#214]
Using the latest version, I no longer get the function names in the sidebar, but instead I get the long titles. I think this relates to the discussion we had recently. Screenshot:

![Screenshot 2023-12-12 150319](https://github.com/etiennebacher/altdoc/assets/987057/fba20632-0e0e-426c-966a-f18e51f18504)

**Comment by etiennebacher** [comment]
I'll take a look when I have some time but things are a bit busy right now. 

Just for ref, I changed the title of the qmd file in #208 but this only changed the .qmd file generated. If the sidebar title is extracted from the .qmd title then this could be the cause

**Comment by vincentarelbundock** [comment]
Yes, that sounds right. In Quarto, the sidebar is built from the title of documents. We would have to the names ourselves if we don't want that, which is kind of burdensome.

**Comment by etiennebacher** [comment]
The solution would be to specify custom names in `_quarto.yml`. For example, this part of asidebar:
```yml
        contents:
          - man/emfx.qmd
          - man/etwfe.qmd
 ```
would become 
```yml
        contents:
          - text: emfx
            href: man/emfx.qmd
          - text: etwfe
            href: man/etwfe.qmd
 ```
This can in `.import_man()`
