### ISSUE TITLE
`$ALTDOC_MAN_BLOCK` is not correctly parsed in the sidebar of  `website_quarto`

### ISSUE THREAD

**Issue by kazuyanagimoto** [etiennebacher/altdoc#266]
Hi @etiennebacher and @vincentarelbundock.  Thank you for the amazing work of introducing modern documentation tools to R packages! I tried to migrate my package documentation to `website_quarto`.
https://github.com/kazuyanagimoto/quartomonothemer

However, all the `man/*.Rd` files are named as `qmd` in the sidebar of the sidebar's Reference section, and as a result, the links to the reference document are broken.
<img width="212" alt="Screenshot 2024-04-01 011855" src="https://github.com/etiennebacher/altdoc/assets/36108423/c141e1ab-2584-46db-9676-78b7b8b32b53">

It seems that all the related `*.qmd` and `*.html` is correctly rendered but `_quarto/_quarto.yml`'s sidebar section is not correctly generated. Here I put the generated `_quarto/_quarto.yml`

```yaml
project:
  type: website
  output-dir: ../docs/
website:
  title: quartomonothemer
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/kazuyanagimoto/quartomonothemer
        aria-label: quartomonothemer GitHub
  sidebar:
    collapse-level: 1
    contents:
      - text: Home
        file: index.qmd
      - section: Reference
        contents:
          - text: qmd
            file: qmd
          - text: qmd
            file: qmd
          - text: qmd
            file: qmd
      - text: News
        file: NEWS.md
      - text: License
        file: LICENSE.md
      - text: Citation
        file: CITATION.md
```
