### ISSUE TITLE
Remove `downlit`

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#278]
Quarto has built-in functionality which respects highlight styles. I wasted my time implementing this and got a subpar result. All we need is to change the template to something like:

```yaml
format:
  html:
    toc: true
    highlight-style: atom-one
    code-link: true
    code-copy: true
    code-overflow: scroll
```
