### ISSUE TITLE
Group reference manual topics into common sections

### ISSUE THREAD

**Issue by grantmcdermott** [etiennebacher/altdoc#297]
Hi folks.

`pkgdown` has the rather nice feature of being able to group (and order) common help documentation topics into different sections. See https://pkgdown.r-lib.org/reference/build_reference.html#reference-index

Does altdoc have similar functionality? I've looked around but couldn't really see how to customize the `$ALTDOC_MAN_BLOCK` section. Apologies if I missed something obvious!

Cheers.

**Comment by etiennebacher** [comment]
You can do this by hand in `altdoc/quarto_website.yml`. For this you need to remove `$ALTDOC_MAN_BLOCK` and have this instead:

```
      - section: Reference
        contents:

        - section: foo
          contents:
          - text: draw_legend
            file: man/draw_legend.qmd
          - text: get_saved_par
            file: man/get_saved_par.qmd
          - text: tinyplot
            file: man/tinyplot.qmd

        - section: bar
          contents:
          - text: tpar
            file: man/tpar.qmd
          - text: type_boxplot
            file: man/type_boxplot.qmd
          - text: type_errorbar
            file: man/type_errorbar.qmd
          - text: type_glm
            file: man/type_glm.qmd
          - text: type_histogram
            file: man/type_histogram.qmd
          - text: type_jitter
            file: man/type_jitter.qmd
          - text: type_lm
            file: man/type_lm.qmd
          - text: type_loess
            file: man/type_loess.qmd
          - text: type_polypath
            file: man/type_polypath.qmd
```
which renders like that:

![image](https://github.com/user-attachments/assets/d211aeeb-e8e4-493d-a924-ed8f65c501cb)

I don't think we can make much more than that. `pkgdown` has those helpers to select a bunch of functions at once but I don't know if that's worth implementing for now.
