### ISSUE TITLE
Manual index page

### ISSUE THREAD

**Issue by zeileis** [etiennebacher/altdoc#326]
One feature that I like about `pkgdown` and am still missing in `altdoc` is the possibility to structure the documentation in the YAML configuration which will then generate an index page with sections. 

As an example consider the "Reference" landing page of <https://Formula.R-Forge.R-project.org/> which looks like this:

![Screenshot of reference index page on the Formula pkdown page](https://github.com/user-attachments/assets/5e106578-0dc5-4092-ab19-57b043a849ec)

This is generated automatically based on this section in the YAML configuration:

```
reference:
  - title: "Extended model formulas"
    contents: 
      - Formula
  - title: "Methods"
    contents: 
      - model.frame.Formula
```

Of course, with so few individual pages this structure is not so important but for bigger packages it is very useful.

In `altdoc/quarto_website.yml` one could use a similar structure (possibly with `man:` or `documentation:` instead of `reference:`) and then generate a `man/index.qmd` from it. Additionally, the same structure could go in the `$ALTDOC_MAN_BLOCK` (see also #325 on using navbar and/or sidebar for this).

I'm happy to help with this but - as discussed with @etiennebacher in person today - I would need guidance where to put what...

P.S.: Thank you both for the amazing package, I'm a big fan!
